name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    
    - name: Install lcov
      run: sudo apt-get install lcov
      
    - name: install grcov
      run: cargo install grcov
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Run grcov
      env:
         PROJECT_NAME: "lfspull"
         RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
         CARGO_INCREMENTAL: 0
      run: |
         cargo build --verbose
         cargo test --verbose
         grcov cov.zip -s . -t lcov --llvm --ignore-not-existing --ignore "/*" -o lcov.info
         
    - name: Push grcov results to Coveralls via GitHub Action
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "lcov.info"
        
